### ISSUE TITLE
Inheritance Exercise

### ISSUE THREAD

**Issue by ramonborba** [ramonborba/EEL7323#2]
Develop a professor/student record system
[Inheritance Exercise](https://gse.ufsc.br/bezerra/disciplinas/cpp/material/exercicio_heranca.html)

**Task List:**
- [x] Implement Pessoa class
- [x] Adapt Aluno and reg_aluno classes
- [x] Implement Professor class
- [x] Implement reg_prof class
- [x] Implement main menu
- [x] #1
- [x] #3

---

If time allows:
- [ ] #4
- [ ] #5
